title: "ZXY-CC-3ag13's Blog"
author: "ZXY-CC-3ag13"
description: "Copyright © ZXY-CC-3ag13 2022"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {title: Portfolio, url: "https://zxy-cc-3ag13.github.io"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "https://zxy-cc-3ag13.github.io/#contact"}
  - {title: Github, icon: github, url: "https://github.com/ZXY-CC-3ag13/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
disqus_shortname: "zxy-cc-3ag13"    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
